package model;

import java.util.EventObject;

/**
 * Tic tac toe event is used to represent an event generated by the the model. This is used to updated the view.
 *
 * @author Mohamed Radwan
 */
@SuppressWarnings("serial")
public class TicTacToeEvent extends EventObject {

    /**
     * X location on the board.
     */
    private int x;
    /**
     * Y location on the board.
     */
    private int y;
    /**
     * Player Turn O if turn is true, X if turn is false.
     */
    private boolean turn;
    /**
     * Current status of the game represented in an enum object.
     */
    private Status status;

    /**
     * Instantiates a new Tic tac toe event.
     *
     * @param source the source of the Event.
     * @param x      the x location on the board.
     * @param y      the y location on the board.
     * @param turn   the turn in the game - O if true, X if false.
     * @param status the status of the game.
     */
    public TicTacToeEvent(TicTacToeModel source, int x, int y, boolean turn, Status status) {
        super(source);
        this.x = x;
        this.y = y;
        this.turn = turn;
        this.status = status;
    }

    /**
     * Gets the x location on the board.
     *
     * @return the x
     */
    public int getX() {
        return x;
    }

    /**
     * Gets the y location on the board.
     *
     * @return the y
     */
    public int getY() {
        return y;
    }

    /**
     * Gets the current player's turn.
     *
     * @return the turn
     */
    public boolean getTurn() {
        return turn;
    }

    /**
     * Gets the status of the game.
     *
     * @return the status
     */
    public Status getStatus() {
        return status;
    }

}
